name: leafspy
channels:
   - conda-forge
   - defaults
dependencies:
   - python >3.8, <3.12
   - cellpy
   - pip
   - Flask
   - Werkzeug
   - pip:
       - galvani
       - pytest
       - black
       - psycopg2
