name: leafspy
channels:
   - conda-forge
   - defaults
dependencies:
   - python >=3.7
   - pip
   - backcall==0.2.0
   - cellpy==0.4.0
   - certifi==2021.5.30
   - cffi==1.14.6
   - charset-normalizer==2.0.3
   - click==8.0.1
   - colorama==0.4.4
   - cycler==0.10.0
   - debugpy==1.4.1
   - decorator==5.0.9
   - Deprecated==1.2.12
   - Flask==2.0.1
   - idna==3.2
   - ipykernel==6.0.3
   - ipython==7.25.0
   - itsdangerous==2.0.1
   - jedi==0.18.0
   - Jinja2==3.0.1
   - kiwisolver==1.3.1
   - MarkupSafe==2.0.1
   - matplotlib==3.4.2
   - matplotlib-inline==0.1.2
   - numpy==1.21.1
   - openpyxl==3.0.7
   - pandas==1.3.1
   - parso==0.8.2
   - pickleshare==0.7.5
   - Pillow==8.3.1
   - prompt-toolkit==3.0.19
   - psycopg2==2.9.1
   - pycparser==2.20
   - PyGithub==1.55
   - Pygments==2.9.0
   - PyJWT==2.1.0
   - PyNaCl==1.4.0
   - pyodbc==4.0.31
   - pyparsing==2.4.7
   - python-box==5.3.0
   - python-dateutil==2.8.2
   - pytz==2021.1
   - pywin32==301
   - pyzmq==22.1.0
   - requests==2.26.0
   - ruamel.yaml==0.17.10
   - scipy==1.7.0
   - six==1.16.0
   - tornado==6.1
   - tqdm==4.61.2
   - traitlets==5.0.5
   - urllib3==1.26.6
   - waitress==2.0.0
   - wcwidth==0.2.5
   - Werkzeug==2.0.1
   - wrapt==1.12.1
   - pip:
       - et-xmlfile==1.1.0
       - ipython-genutils==0.2.0
       - ruamel.yaml.clib==0.2.6
       - galvani==0.2.0
       - jupyter-client==6.1.12
       - jupyter-core==4.7.1
