# This is a basic workflow to help you get started with Actions

name: PyTest

on:
  push:
    branches:
      - "**"

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install action dependencies
      - name: Install mdbtools
        run: |
          sudo apt-get update
          sudo apt-get install -y mdbtools
        
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip pytest
        
      # Install leafspy
      - name: Install dependencies
        run: python -m pip install -e .
        
      # Test with pytest
      - name: Run pytest
        run: |
          echo Running pytest
          pytest --verbose
